"""empty message

Revision ID: 07021995dd44
Revises: 
Create Date: 2024-09-21 20:04:07.756189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07021995dd44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('parish', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('mun', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('ant_fam', sa.String(length=1000), nullable=False),
    sa.Column('ant_per', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=1000), nullable=False),
    sa.Column('recommendations', sa.String(length=1000), nullable=False),
    sa.Column('treatment', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('diagnosis_diff', sa.String(length=1000), nullable=False),
    sa.Column('diagnosis_eco', sa.String(length=1000), nullable=False),
    sa.Column('exams', sa.String(length=1000), nullable=False),
    sa.Column('medications', sa.String(length=1000), nullable=False),
    sa.Column('symtomps', sa.String(length=1000), nullable=False),
    sa.Column('phy_exa', sa.String(length=1000), nullable=False),
    sa.Column('signs', sa.String(length=1000), nullable=False),
    sa.Column('observations', sa.String(length=1000), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pesos', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.Column('pay_mov', sa.Float(), nullable=False),
    sa.Column('biopago', sa.Float(), nullable=False),
    sa.Column('point', sa.Float(), nullable=False),
    sa.Column('id_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_record'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record__obst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_births', sa.Integer(), nullable=False),
    sa.Column('num_abort', sa.Integer(), nullable=False),
    sa.Column('menst_date', sa.Date(), nullable=False),
    sa.Column('type_preg', sa.String(length=20), nullable=False),
    sa.Column('id_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_record'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record__obst')
    op.drop_table('pay')
    op.drop_table('record')
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
