"""empty message

Revision ID: 8d078ee78a29
Revises: bf3097d7722b
Create Date: 2024-09-23 10:35:38.766825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d078ee78a29'
down_revision = 'bf3097d7722b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_pat', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('type_pat')

    # ### end Alembic commands ###
